const experiences=[
{id:'deck',name:'Golden-hour deck walk',time:'17:45',duration:'30 minutes',kind:'ON THE SHIP',where:'Open-air deck',description:'Take a quiet moment on deck as the light softens over the waterfront.',details:'A self-guided moment for fresh air and waterfront views. Bring a light layer and wear comfortable, non-slip shoes. Access to outdoor areas depends on the vessel, weather and crew instructions.'},
{id:'dinner',name:'Dinner on the water',time:'18:30',duration:'90 minutes',kind:'ONBOARD DINING',where:'Dining deck',description:'Settle in for good food, good company and an ever-changing view.',details:'An illustrative dining experience. Menus, seating times, dietary options and inclusions depend on the cruise you book. Contact the operator before booking to confirm accessibility and dietary requirements.'},
{id:'shore',name:'A waterfront wander',time:'16:00',duration:'45 minutes',kind:'BEFORE YOU BOARD',where:'Departure waterfront',description:'Arrive a little early and explore the waterfront before your cruise.',details:'A suggested independent walk before boarding, rather than an operator-led excursion. Confirm your departure location and check-in time first. Allow plenty of time to return; no shore stop during the sailing is implied.'}
];
let plan=[{id:'boarding',name:'Welcome aboard',time:'17:00',where:'Departure point · confirm with operator'},experiences[0],experiences[1]];
const el=id=>document.getElementById(id);let toastTimer;
function toast(message){el('toast').textContent=message;el('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el('toast').classList.remove('show'),3000)}
function render(){el('count').textContent=`${plan.length} experience${plan.length===1?'':'s'}`;el('plan').replaceChildren();for(const item of [...plan].sort((a,b)=>a.time.localeCompare(b.time))){const row=document.createElement('div');row.className='plan-item';const time=document.createElement('time');time.textContent=item.time;const copy=document.createElement('div');const title=document.createElement('h4');title.textContent=item.name;const desc=document.createElement('p');desc.textContent=item.where;copy.append(title,desc);const remove=document.createElement('button');remove.className='remove';remove.textContent='Remove';remove.setAttribute('aria-label',`Remove ${item.name} from plan`);remove.onclick=()=>{plan=plan.filter(p=>p.id!==item.id);render();toast('Removed from your draft plan')};row.append(time,copy,remove);el('plan').append(row)}if(!plan.length){const p=document.createElement('p');p.textContent='Your plan is empty. Add an experience below.';el('plan').append(p)}document.querySelectorAll('[data-add]').forEach(b=>{const added=plan.some(p=>p.id===b.dataset.add);b.disabled=added;b.textContent=added?'In your plan':'Add to plan'})}
function add(id){const item=experiences.find(x=>x.id===id);if(!item)throw new Error('Unknown experience');if(!plan.some(p=>p.id===id)){plan.push(item);render();toast('Added to your draft plan')}return {id,added:true,total:plan.length}}
function details(item){el('detail-content').innerHTML=`<p class="eyebrow">${item.kind} · SAMPLE EXPERIENCE</p><h2>${item.name}</h2><p>${item.duration} · ${item.where}</p><p>${item.details}</p><p class="small">Suggested time: ${item.time}. This is a draft plan, not a reservation.</p><button class="button" data-add="${item.id}">Add to plan</button>`;el('detail-content').querySelector('button').onclick=()=>add(item.id);render();el('details').showModal()}
for(const item of experiences){const card=document.createElement('article');card.className='experience';card.innerHTML=`<span class="eyebrow">${item.kind}</span><h3>${item.name}</h3><p>${item.description}</p><span class="meta">${item.duration} · Sample experience</span><div class="actions"><button class="details-button">View details</button><button class="button" data-add="${item.id}">Add to plan</button></div>`;card.querySelector('.details-button').onclick=()=>details(item);card.querySelector('[data-add]').onclick=()=>add(item.id);el('experiences').append(card)}
el('details').querySelector('.close').onclick=()=>el('details').close();el('details').addEventListener('click',event=>{if(event.target===el('details')){const rect=el('details').getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)el('details').close()}});
const urls={victoria:'https://www.melbourneboatparties.org/',lady:'https://ladycutler.com.au/',charter:'https://australianboatcharters.com.au/'};el('book').onclick=()=>window.open(urls[el('ship').value],'_blank','noopener');
el('download').onclick=()=>{const text='MY DAY ON THE WATER\nAustralian Boat Parties · Draft plan\n\n'+[...plan].sort((a,b)=>a.time.localeCompare(b.time)).map(p=>`${p.time}  ${p.name}\n       ${p.where}`).join('\n\n')+'\n\nSample schedule only. This is not a booking or confirmed itinerary. Confirm times and availability with the operator.\nhttps://australianboatparties.com/\n';const blob=new Blob([text],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='my-cruise-plan.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Your draft plan has been downloaded')};
const reduce=matchMedia('(prefers-reduced-motion: reduce)');let ticking=false;function paint(){const stage=document.querySelector('.stage');const progress=Math.min(1,Math.max(0,scrollY/(innerHeight*.5)));if(!reduce.matches){stage.style.setProperty('--zoom',1.02+progress*.12);stage.style.setProperty('--rise',`${-progress*55}px`);stage.style.setProperty('--fade',1-progress*.6)}ticking=false}addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(paint);ticking=true}},{passive:true});render();paint();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'add_draft_cruise_experience',description:'Add a sample experience to the current unsaved cruise draft. Does not create a booking.',inputSchema:{type:'object',properties:{experienceId:{type:'string',enum:experiences.map(e=>e.id)}},required:['experienceId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input.experienceId!=='string'||Object.keys(input).some(k=>k!=='experienceId'))throw new Error('Invalid experience input');return add(input.experienceId)}})).catch(()=>{})}catch{}}
